import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdtempSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { test } from 'node:test';
import WebSocket from 'ws';
import { Hive } from './hive.ts';
import { startServer } from './serve.ts';
import { saveAdaptiveRouting } from './adaptive-config.ts';
import { jevTopologyResponse } from './fixtures/jev-topology.ts';
import type { AdaptiveExecutionState, AdaptiveRoutingEvent, AdaptiveTopology } from '../shared/adaptive-topology.ts';
import { countRows } from './test-fixtures.ts';

test('the Human websocket receives every piece of advice; agents only get it in their own responses', { timeout: 15000 }, async t => {
  const dir = mkdtempSync(path.join(os.tmpdir(), 'hive-routing-realtime-'));
  const hive = new Hive(path.join(dir, 'hive.db'));
  const human = hive.identity.getAgent('human');
  const brain = hive.identity.join({ role: 'brain', project: 'chapter' });
  for (let i = 0; i < 2; i++) hive.identity.join({ role: 'worker', seniority: 'senior', project: 'chapter' });
  const dm = hive.channels.openDm(human, brain.agent.name);
  const server = startServer({ hive, port: 0, telegram: false });
  let socket: WebSocket | undefined;
  t.after(async () => {
    socket?.terminate(); await hive.adaptiveTopology.stop(); await server.shutdown();
    hive.db.close(); rmSync(dir, { recursive: true, force: true });
  });
  const nativeFetch = globalThis.fetch;
  let target: AdaptiveTopology = 'single', unavailable = false;
  t.mock.method(globalThis, 'fetch', async (url: string | URL | Request, init?: RequestInit) => {
    if (String(url) !== 'https://api.typesafe.ai/v1/systemone') return nativeFetch(url, init);
    if (unavailable) throw new Error('Fixture unavailable');
    return Response.json(jevTopologyResponse(String(init?.body), target));
  });
  saveAdaptiveRouting(dir, { enabled: true, apiKey: 'not-a-live-key' });
  const base = `http://127.0.0.1:${await server.ready}`;
  const session = await fetch(`${base}/api/ui/session`, { method: 'POST', headers: { origin: base, 'content-type': 'application/json' }, body: '{}' });
  assert.equal(session.status, 200); const cookie = session.headers.get('set-cookie')!.split(';')[0]!;
  await session.arrayBuffer();
  socket = new WebSocket(base.replace('http:', 'ws:') + '/ws', { headers: { origin: base, cookie } });
  type Frame = { type: string; payload: { event: AdaptiveRoutingEvent; state: AdaptiveExecutionState; channelId: string } };
  const frames: Frame[] = [];
  socket.on('message', raw => frames.push(JSON.parse(String(raw)) as Frame));
  await once(socket, 'open');
  const nextRouting = () => new Promise<Frame>(resolve => {
    const listener = (raw: WebSocket.RawData) => {
      const frame = JSON.parse(String(raw)) as Frame;
      if (frame.type === 'adaptive-routing') { socket!.off('message', listener); resolve(frame); }
    };
    socket!.on('message', listener);
  });
  let pending = nextRouting();
  const started = await hive.adaptiveTopology.routeHumanRequest(human, { channel: dm.id, body: 'Perform the bounded request.', requestId: 'start' });
  assert.ok(started); const initial = await pending;
  assert.equal(initial.payload.state.monitoring, 'active');
  assert.equal(initial.payload.state.advice?.plan, 'single');
  const messagesBefore = countRows(hive, 'messages');
  const act = () => hive.adaptiveTopology.adviseBrainAction(brain.agent, { kind: 'brain_message', channelId: dm.id, summary: 'progress' });
  pending = nextRouting(); unavailable = true;
  assert.equal((await act())?.state, 'unavailable');
  const failed = await pending; assert.equal(failed.payload.event.kind, 'advice');
  assert.equal(failed.payload.state.advice?.state, 'unavailable');
  pending = nextRouting(); unavailable = false; target = 'brain_multi_room';
  assert.equal((await act())?.plan, 'brain_multi_room_2');
  const recovered = await pending;
  assert.equal(recovered.payload.state.advice?.topology, 'brain_multi_room');
  assert.ok((recovered.payload.state.revision ?? 0) > (failed.payload.state.revision ?? 0));
  assert.equal(countRows(hive, 'messages'), messagesBefore, 'advice never becomes a message');
  const agent = await fetch(`${base}/api/agent/me`, { headers: { authorization: `Bearer ${brain.token}` } });
  const me = await agent.json() as Record<string, unknown>;
  assert.equal('adaptiveRouting' in me || 'adaptiveExecutions' in me, false);
  const forbidden = await fetch(`${base}/api/ui/channels/${dm.id}/adaptive-routing`, { headers: { authorization: `Bearer ${brain.token}` } });
  assert.equal(forbidden.status, 401); await forbidden.arrayBuffer();
  const disabled = await fetch(`${base}/api/ui/adaptive-routing`, { method: 'PUT', headers: { origin: base, cookie, 'content-type': 'application/json' }, body: JSON.stringify({ enabled: false }) });
  assert.equal(disabled.status, 200); await disabled.arrayBuffer();
  const retained = await fetch(`${base}/api/ui/channels/${dm.id}/adaptive-routing`, { headers: { origin: base, cookie } });
  const view = await retained.json() as { state: AdaptiveExecutionState; events: AdaptiveRoutingEvent[] };
  assert.equal(view.state.monitoring, 'disabled'); assert.equal(view.events.length, 3);
  assert.equal(frames.filter(frame => frame.type === 'adaptive-routing').length, 3);
});
