import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdtempSync, rmSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { Hive } from "./hive.ts";
import { startServer } from "./serve.ts";

test("Human recovery is revision-fenced, durable, transactional and supersedes old waits/ACKs", { timeout: 15_000 }, async t => {
  const dir = mkdtempSync(path.join(os.tmpdir(), "hive-recovery-"));
  let hive = new Hive(path.join(dir, "hive.db"));
  t.after(() => { hive.db.close(); rmSync(dir, { recursive: true, force: true }); });
  const human = hive.getAgent("human"), worker = hive.join({ role: "worker", seniority: "mid" });
  const project = worker.agent.projectId!;
  assert.throws(() => hive.join({ role: "worker", seniority: "mid", resumeName: worker.agent.name }), /valid token/);
  assert.throws(() => hive.join({ role: "worker", seniority: "mid", token: "expired", resumeName: worker.agent.name }), /Human-authorized/);
  assert.throws(() => hive.changeAgentCredential(worker.agent, project, worker.agent.id, { action: "rotate", expectedRevision: 1 }), /Only Human/);
  const session = hive.openInboxSession(worker.agent, randomUUID());
  const dm = hive.openDm(human, worker.agent.name);
  hive.postMessage(human, { channel: dm.id, body: "remain unacknowledged across credential rotation" });
  const offered = await hive.wait(worker.agent, 100, undefined, { sessionId: session });
  hive.db.exec("CREATE TEMP TRIGGER reject_credential BEFORE INSERT ON agent_credentials BEGIN SELECT RAISE(ABORT,'injected'); END;");
  assert.throws(() => hive.changeAgentCredential(human, project, worker.agent.id, { action: "rotate", expectedRevision: 1 }), /injected/);
  assert.equal(hive.agentByToken(worker.token).id, worker.agent.id);
  assert.equal(hive.inbox.currentSession(worker.agent.id), session);
  hive.db.exec("DROP TRIGGER reject_credential");
  const changed = hive.changeAgentCredential(human, project, worker.agent.id, { action: "rotate", expectedRevision: 1 });
  assert.ok(changed.token); assert.equal(changed.credential.revision, 2);
  assert.throws(() => hive.agentByToken(worker.token), /Invalid token/);
  assert.throws(() => hive.acknowledgeInbox(worker.agent, session, offered.delivery!.id), /superseded/);
  assert.throws(() => hive.changeAgentCredential(human, project, worker.agent.id, { action: "rotate", expectedRevision: 1 }), /changed/);
  const current = hive.agentByToken(changed.token);
  const currentSession = hive.openInboxSession(current, randomUUID());
  const replay = await hive.wait(current, 100, undefined, { sessionId: currentSession });
  assert.equal(replay.delivery!.id, offered.delivery!.id);
  hive.acknowledgeInbox(current, currentSession, replay.delivery!.id);
  const wait = hive.wait(current, 5000, undefined, { sessionId: currentSession });
  const cancelled = assert.rejects(wait, /superseded/);
  hive.changeAgentCredential(human, project, worker.agent.id, { action: "revoke", expectedRevision: 2 });
  await cancelled;
  hive.db.close(); hive = new Hive(path.join(dir, "hive.db"));
  assert.equal(hive.agentCredential(hive.getAgent("human"), project, worker.agent.id).credential.revoked, true);
  assert.throws(() => hive.agentByToken(changed.token!), /Invalid token/);
});

test("resume worktree and Human HTTP credential gates preserve project and actor constraints", { timeout: 15_000 }, async t => {
  const dir = mkdtempSync(path.join(os.tmpdir(), "hive-recovery-http-"));
  const hive = new Hive(path.join(dir, "hive.db")), service = startServer({ hive, port: 0, telegram: false });
  t.after(async () => { await service.shutdown(); hive.db.close(); rmSync(dir, { recursive: true, force: true }); });
  const human = hive.getAgent("human"), first = hive.join({ role: "brain" });
  hive.createProject(human, { name: "Other", slug: "other", worktree: path.join(dir, "other") });
  assert.throws(() => hive.join({ role: "brain", token: first.token, cwd: path.join(dir, "other") }), /project cannot change/);
  assert.throws(() => hive.join({ role: "worker", seniority: "mid", token: first.token }), /role cannot change/);
  assert.equal(hive.join({ role: "brain", token: first.token, project: "chapter" }).created, false);
  const base = `http://127.0.0.1:${await service.ready}`;
  const url = `${base}/api/ui/projects/${first.agent.projectId}/agents/${first.agent.id}/credential`;
  const denied = await fetch(url, { method: "POST", headers: { authorization: `Bearer ${first.token}`, "content-type": "application/json" }, body: JSON.stringify({ action: "rotate", expectedRevision: 1 }) });
  assert.ok([401,403].includes(denied.status)); await denied.body?.cancel();
  const bootstrap = await fetch(`${base}/api/ui/session`, { method: "POST", headers: { origin: base, "content-type": "application/json" }, body: "{}" });
  const cookie = bootstrap.headers.get("set-cookie")!.split(";",1)[0]!;
  await bootstrap.body?.cancel();
  const state = await fetch(url, { headers: { origin: base, cookie } });
  assert.equal(state.status, 200); assert.ok(!JSON.stringify(await state.json()).includes(first.token));
  const wrongRole = await fetch(url, { method: "POST", headers: { origin: base, cookie, authorization: `Bearer ${first.token}`, "content-type": "application/json" }, body: "{}" });
  assert.equal(wrongRole.status, 403); await wrongRole.body?.cancel();
  const changed = await fetch(url, { method: "POST", headers: { origin: base, cookie, "content-type": "application/json" }, body: JSON.stringify({ action: "rotate", expectedRevision: 1 }) });
  assert.equal(changed.status, 200, await changed.text());
});
