import assert from "node:assert/strict";
import { cpSync, existsSync, mkdtempSync, readFileSync, rmSync, statSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import { test, type TestContext } from "node:test";
import { Hive } from "./hive.ts";
import { STORAGE_VERSION } from "./storage-migrations.ts";
import { failWrites, findRow, insertRow, readValue } from "./test-fixtures.ts";

function temp(t: TestContext) {
  const dir = mkdtempSync(path.join(os.tmpdir(), "hive-migrations-"));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  return { dir, file: path.join(dir, "hive.db") };
}

// Literal supported pre-project table shapes; deliberately not generated by the migration under test.
function legacy(file: string, chatColumn = false) {
  const db = new DatabaseSync(file);
  db.exec(`
    CREATE TABLE agents (id TEXT PRIMARY KEY, name TEXT UNIQUE NOT NULL, role TEXT NOT NULL, seniority TEXT, focus TEXT,
      token_hash TEXT NOT NULL, online INTEGER NOT NULL DEFAULT 0, last_seen_at INTEGER NOT NULL, created_at INTEGER NOT NULL,
      inbox_cursor INTEGER NOT NULL DEFAULT 0);
    CREATE TABLE channels (id TEXT PRIMARY KEY, name TEXT NOT NULL, type TEXT NOT NULL, topic TEXT, created_by TEXT NOT NULL, created_at INTEGER NOT NULL);
    CREATE TABLE messages (seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT UNIQUE NOT NULL, channel_id TEXT NOT NULL,
      thread_id TEXT, author_id TEXT NOT NULL, body TEXT NOT NULL, kind TEXT NOT NULL DEFAULT 'chat', control TEXT,
      mentions TEXT NOT NULL DEFAULT '[]', created_at INTEGER NOT NULL);
    CREATE TABLE telegram_hold (telegram_message_id INTEGER PRIMARY KEY, telegram_thread_id INTEGER NOT NULL, payload TEXT NOT NULL);
    CREATE TABLE telegram_out (telegram_message_id INTEGER PRIMARY KEY, seq INTEGER NOT NULL, channel_id TEXT NOT NULL, thread_id TEXT);
    CREATE TABLE telegram_topics (channel_id TEXT PRIMARY KEY, telegram_thread_id INTEGER NOT NULL UNIQUE);
    INSERT INTO agents VALUES ('worker', 'Fixture', 'worker', 'mid', NULL, 'fixture', 0, 1, 1, 0);
    INSERT INTO channels VALUES ('general', 'general', 'public', NULL, 'human', 1), ('private', 'private', 'private', NULL, 'human', 2);
    INSERT INTO messages VALUES (1, 'root', 'general', NULL, 'worker', 'fixture', 'chat', NULL, '[]', 1);
    INSERT INTO telegram_hold VALUES (7, 11, '{"fixture":1}'), (8, 12, '{"fixture":2}');
    INSERT INTO telegram_out VALUES (7, 1, 'general', 'root'), (8, 1, 'private', NULL);
    INSERT INTO telegram_topics VALUES ('general', 11), ('private', 12);
  `);
  if (chatColumn) {
    for (const table of ["telegram_hold", "telegram_out", "telegram_topics"]) {
      db.exec(`ALTER TABLE ${table} ADD COLUMN telegram_chat_id INTEGER; UPDATE ${table} SET telegram_chat_id = -123`);
    }
  }
  db.close();
}

function snapshot(file: string) {
  const db = new DatabaseSync(file);
  try {
    const schema = db.prepare("SELECT type, name, tbl_name, sql FROM sqlite_master ORDER BY type, name").all();
    const tables = db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name").all() as { name: string }[];
    const rows = tables.map(({ name }) => [name, db.prepare(`SELECT * FROM "${name.replaceAll('"', '""')}" ORDER BY rowid`).all()]);
    return { schema, rows, version: db.prepare("PRAGMA user_version").get() };
  } finally { db.close(); }
}

for (const chatColumn of [false, true]) {
  test(`legacy mappings, row contents and relationships survive upgrade and restart (chat column: ${chatColumn})`, (t) => {
    const { file } = temp(t);
    legacy(file, chatColumn);
    const hive = new Hive(file);
    try {
      // schema-level assertion: migrated table shapes and rewritten legacy rows.
      assert.equal((hive.db.prepare("PRAGMA user_version").get() as { user_version: number }).user_version, STORAGE_VERSION);
      const expectedChat = chatColumn ? -123 : 0;
      assert.deepEqual(hive.db.prepare("SELECT telegram_chat_id, telegram_message_id, payload FROM telegram_hold ORDER BY telegram_message_id").all().map((r) => ({ ...r })), [
        { telegram_chat_id: expectedChat, telegram_message_id: 7, payload: '{"fixture":1}' },
        { telegram_chat_id: expectedChat, telegram_message_id: 8, payload: '{"fixture":2}' },
      ]);
      assert.equal(hive.db.prepare("SELECT channel_id FROM telegram_out WHERE thread_id = 'root'").get()?.channel_id, "general");
      assert.equal(hive.db.prepare("SELECT telegram_chat_id FROM telegram_topics WHERE channel_id = 'general'").get()?.telegram_chat_id, chatColumn ? -123 : null);
      assert.equal(hive.getAgent("worker").projectId, hive.getChannel("general").projectId);
    } finally { hive.db.close(); }
    const once = snapshot(file);
    new Hive(file).db.close();
    assert.deepEqual(snapshot(file), once);
  });
}

test("fresh install and an unversioned current-main database are idempotent", (t) => {
  const { file } = temp(t);
  const first = new Hive(file);
  first.db.exec("PRAGMA user_version = 0"); // schema-level assertion
  first.db.close();
  const second = new Hive(file);
  second.db.close();
  const once = snapshot(file);
  new Hive(file).db.close();
  assert.deepEqual(snapshot(file), once);
});

const faults: Array<{ name: string; sql: RegExp; before?: boolean }> = [];
for (const table of ["telegram_hold", "telegram_out", "telegram_topics"]) {
  for (const [label, sql] of [
    ["create", new RegExp(`^CREATE TABLE _hive_migrate_${table} `)],
    ["copy", new RegExp(`^INSERT INTO _hive_migrate_${table} `)],
    ["drop", new RegExp(`^DROP TABLE ${table}$`)],
    ["swap", new RegExp(`^ALTER TABLE _hive_migrate_${table} RENAME`)],
  ] as const) faults.push({ name: `${table} after ${label}`, sql });
}
for (const table of ["agents", "channels"]) faults.push({ name: `after ${table} ALTER`, sql: new RegExp(`^ALTER TABLE ${table} ADD COLUMN`) });
faults.push({ name: "before version", sql: /^PRAGMA user_version =/, before: true });
faults.push({ name: "after version", sql: /^PRAGMA user_version =/ });
faults.push({ name: "before commit", sql: /^COMMIT$/, before: true });

for (const fault of faults) {
  test(`startup rollback, closed handle and retry: ${fault.name}`, (t) => {
    const { file } = temp(t);
    legacy(file);
    const before = snapshot(file);
    const original = DatabaseSync.prototype.exec;
    let readFailedDb: (() => unknown) | undefined;
    const stub = t.mock.method(DatabaseSync.prototype, "exec", function (this: DatabaseSync, sql: string) {
      const hit = fault.sql.test(sql);
      if (hit) readFailedDb = () => this.prepare("SELECT 1");
      if (hit && fault.before) throw new Error("injected migration failure");
      original.call(this, sql);
      if (hit) throw new Error("injected migration failure");
    });
    assert.throws(() => new Hive(file), /injected migration failure/);
    stub.mock.restore();
    assert.ok(readFailedDb);
    assert.throws(readFailedDb, /not open|closed/i);
    assert.deepEqual(snapshot(file), before);
    new Hive(file).db.close();
    const after = snapshot(file);
    new Hive(file).db.close();
    assert.deepEqual(snapshot(file), after);
  });
}

for (const table of ["telegram_hold", "telegram_out", "telegram_topics"]) {
  test(`a real SQLite failure midway through copying ${table} rolls back every earlier step`, (t) => {
    const { file } = temp(t);
    legacy(file);
    const before = snapshot(file);
    const original = DatabaseSync.prototype.exec;
    const stub = t.mock.method(DatabaseSync.prototype, "exec", function (this: DatabaseSync, sql: string) {
      original.call(this, sql);
      if (sql.startsWith(`CREATE TABLE _hive_migrate_${table} `)) {
        const condition = table === "telegram_topics" ? "NEW.channel_id = 'private'" : "NEW.telegram_message_id = 8";
        original.call(this, `CREATE TRIGGER fail_copy BEFORE INSERT ON _hive_migrate_${table} WHEN ${condition}
          BEGIN SELECT RAISE(ABORT, 'injected row-copy failure'); END`);
      }
    });
    assert.throws(() => new Hive(file), /injected row-copy failure/);
    stub.mock.restore();
    assert.deepEqual(snapshot(file), before);
    new Hive(file).db.close();
  });
}

for (const mutation of [
  "PRAGMA user_version = 99",
  "DROP TABLE telegram_hold",
  "ALTER TABLE telegram_out RENAME TO old_out; CREATE TABLE telegram_out AS SELECT * FROM old_out; DROP TABLE old_out",
  "CREATE TABLE _hive_migrate_telegram_hold (unexpected TEXT)",
  "CREATE UNIQUE INDEX invalid_global_topic ON telegram_topics(telegram_thread_id)",
]) {
  test(`reject inconsistent/version-unknown current schemas without mutations: ${mutation}`, (t) => {
    const { file } = temp(t);
    const hive = new Hive(file);
    hive.db.exec(mutation); // schema-level assertion
    hive.db.close();
    const before = snapshot(file);
    assert.throws(() => new Hive(file), /Invalid storage schema|Unsupported storage schema/);
    assert.deepEqual(snapshot(file), before);
  });
}

test("unversioned lookalike tables without the composite key are rejected rather than marked migrated", (t) => {
  const { file } = temp(t);
  const hive = new Hive(file);
  // schema-level assertion
  hive.db.exec("PRAGMA user_version = 0; ALTER TABLE telegram_hold RENAME TO old_hold; CREATE TABLE telegram_hold AS SELECT * FROM old_hold; DROP TABLE old_hold");
  hive.db.close();
  const before = snapshot(file);
  assert.throws(() => new Hive(file), /primary key/);
  assert.deepEqual(snapshot(file), before);
});

test("project, channel, DM, join and invitation failures roll back all rows and emit no events", (t) => {
  const { file } = temp(t);
  const hive = new Hive(file);
  t.after(() => hive.db.close());
  const human = hive.getAgent("human");
  const brain = hive.join({ role: "brain" }).agent;
  const worker = hive.join({ role: "worker", seniority: "mid" }).agent;
  const room = hive.createChannel(brain, { name: "private", type: "private" });
  const events: string[] = [];
  for (const event of ["agent", "channel", "message", "queued"]) hive.bus.on(event, () => events.push(event));
  const check = (operation: () => unknown, pattern: RegExp) => {
    const before = snapshot(file);
    events.length = 0;
    assert.throws(operation, pattern);
    assert.deepEqual(snapshot(file), before);
    assert.deepEqual(events, []);
  };
  check(() => hive.invite(brain, room.id, [worker.name, "missing-fixture"]), /No agent named/);
  const restoreMembership = failWrites(hive, "channel_members", {
    when: `NEW.agent_id = '${worker.id}'`, message: "injected membership failure", persistent: true,
  });
  check(() => hive.createChannel(brain, { name: "public-fault", type: "public" }), /membership failure/);
  check(() => hive.openDm(brain, worker.name), /membership failure/);
  restoreMembership();
  failWrites(hive, "channel_members", {
    when: "(SELECT type FROM channels WHERE id = NEW.channel_id) = 'brains'", message: "injected brains failure", persistent: true,
  });
  check(() => hive.createProject(human, { name: "Fault", slug: "fault" }), /brains failure/);
  check(() => hive.join({ role: "brain" }), /brains failure/);
});

test("nested creation events are emitted only after another connection can see the committed state", (t) => {
  const { file } = temp(t);
  const hive = new Hive(file);
  const observer = new DatabaseSync(file);
  t.after(() => { observer.close(); hive.db.close(); });
  let channels = 0;
  let messages = 0;
  hive.bus.on("channel", (channel: { id: string }) => {
    channels++;
    assert.ok(observer.prepare("SELECT 1 FROM channels WHERE id = ?").get(channel.id));
    assert.ok(observer.prepare("SELECT 1 FROM channel_members WHERE channel_id = ?").get(channel.id));
  });
  hive.bus.on("message", (message: { id: string }) => {
    messages++;
    assert.ok(observer.prepare("SELECT 1 FROM messages WHERE id = ?").get(message.id));
  });
  const brain = hive.join({ role: "brain" }).agent;
  hive.createChannel(brain, { name: "committed", type: "private" });
  assert.equal(channels, 1);
  assert.equal(messages, 2);
});

test("the documented stopped-home WAL-aware backup restores messages, attachment bytes and Telegram mappings", async (t) => {
  const { dir, file } = temp(t);
  const restored = temp(t);
  const hive = new Hive(file);
  try {
    const human = hive.getAgent("human");
    const attachment = await hive.createFileFromBytes(human, { name: "fixture.txt", mime: "text/plain", bytes: Buffer.from("backup fixture") });
    const message = hive.postMessage(human, { channel: "general", body: "backup", attachmentIds: [attachment.id] });
    insertRow(hive, "telegram_out", { telegram_chat_id: -100, telegram_message_id: 7, seq: message.seq, channel_id: "general", thread_id: null });
    insertRow(hive, "telegram_topics", { channel_id: "general", telegram_thread_id: 11, telegram_chat_id: -100 });
    insertRow(hive, "telegram_hold", { telegram_chat_id: -100, telegram_message_id: 8, telegram_thread_id: 11, payload: "{}" });
    assert.ok(existsSync(`${file}-wal`) && statSync(`${file}-wal`).size > 0);
  } finally { hive.db.close(); }
  // All connections are closed before copying the complete home, including any remaining WAL/SHM files.
  cpSync(dir, restored.dir, { recursive: true });
  const copy = new Hive(restored.file);
  try {
    assert.deepEqual(snapshot(restored.file), snapshot(file));
    const row = findRow(copy, "attachments", {}, ["id", "sha256"]) as { id: string; sha256: string };
    assert.equal(readFileSync(path.join(restored.dir, "files", row.sha256), "utf8"), "backup fixture");
    assert.equal(copy.getAttachment(copy.getAgent("human"), row.id).channelId, "general");
    assert.equal(readValue(copy, "telegram_out", "seq", { telegram_message_id: 7 }), copy.getVisibleMessage(copy.getAgent("human"), 1).seq);
  } finally { copy.db.close(); }
});
