import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import { test, type TestContext } from "node:test";
import { Hive } from "../hive.ts";
import { deleteRows, failWrites, markLegacyStorage, rerunMigration, updateRows } from "../test-fixtures.ts";
import { applyMigrations, initTelegramRouting, LATEST_VERSION, MIGRATIONS, schemaVersion } from "./index.ts";

// Checked-in fixtures generated by the pre-#166 code (commit dc018a7, the last
// release that built the schema ad hoc in each store):
// - main-schema.json: sqlite_master of a fresh hive after every store was opened;
// - main-schema-telegram-routed.json: the same after the Telegram routing migration;
// - main-populated-v2.sql: a populated user_version=2 hive with rows in every table
//   (Telegram routed to a verified bot), dumped as tables, rows, then indexes/triggers.
const fixtures = path.join(path.dirname(new URL(import.meta.url).pathname), "../fixtures/storage");
const fixture = (name: string) => readFileSync(path.join(fixtures, name), "utf8");

type SchemaRow = { type: string; name: string; tbl: string; sql: string };

function schemaOf(db: DatabaseSync): SchemaRow[] {
  return db.prepare("SELECT type, name, tbl_name AS tbl, sql FROM sqlite_master WHERE name NOT LIKE 'sqlite_%' ORDER BY type, name").all()
    .map(row => ({ type: String(row.type), name: String(row.name), tbl: String(row.tbl), sql: String(row.sql ?? "").replace(/\s+/g, " ").trim() }));
}

function tableNames(db: DatabaseSync): string[] {
  return (db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name").all() as { name: string }[]).map(row => row.name);
}

function rowsOf(db: DatabaseSync): Record<string, unknown[]> {
  return Object.fromEntries(tableNames(db).map(name =>
    [name, db.prepare(`SELECT * FROM "${name}" ORDER BY rowid`).all().map(row => ({ ...row }))]));
}

function temp(t: TestContext) {
  const dir = mkdtempSync(path.join(os.tmpdir(), "hive-migration-runner-"));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  return path.join(dir, "hive.db");
}

function inspect<T>(file: string, read: (db: DatabaseSync) => T): T {
  const db = new DatabaseSync(file);
  try { return read(db); } finally { db.close(); }
}

function open(t: TestContext, file: string): Hive {
  const hive = new Hive(file);
  t.after(() => { try { hive.db.close(); } catch { /* already closed by the test */ } });
  return hive;
}

test("the migration list is ordered, contiguous and uniquely named", () => {
  assert.deepEqual(MIGRATIONS.map(m => m.version), MIGRATIONS.map((_, i) => i + 3));
  assert.equal(new Set(MIGRATIONS.map(m => m.name)).size, MIGRATIONS.length);
  assert.equal(LATEST_VERSION, MIGRATIONS.at(-1)!.version);
});

test("a fresh database gets exactly the schema the pre-migration code created", t => {
  const file = temp(t);
  const hive = open(t, file);
  assert.equal(schemaVersion(hive.db), LATEST_VERSION);
  assert.deepEqual(schemaOf(hive.db), JSON.parse(fixture("main-schema.json")));
  initTelegramRouting(hive.db, "bot:1");
  assert.deepEqual(schemaOf(hive.db), JSON.parse(fixture("main-schema-telegram-routed.json")));
});

test("restart is idempotent: nothing is pending and the schema and rows stay unchanged", t => {
  const file = temp(t);
  open(t, file).db.close();
  const before = inspect(file, db => ({ schema: schemaOf(db), rows: rowsOf(db) }));
  const db = new DatabaseSync(file);
  try { assert.deepEqual(applyMigrations(db), []); } finally { db.close(); }
  open(t, file).db.close();
  assert.deepEqual(inspect(file, db => ({ schema: schemaOf(db), rows: rowsOf(db) })), before);
});

test("every baseline migration is idempotent on the current schema (legacy databases rerun them)", t => {
  const db = new DatabaseSync(":memory:");
  t.after(() => db.close());
  applyMigrations(db);
  const before = { schema: schemaOf(db), rows: rowsOf(db) };
  for (const migration of MIGRATIONS) rerunMigration(db, migration.name);
  assert.deepEqual({ schema: schemaOf(db), rows: rowsOf(db) }, before);
});

test("a populated current-main (user_version 2) hive upgrades with every row and the schema preserved", t => {
  const sql = fixture("main-populated-v2.sql");
  const generatedAt = Number(/^-- generated at (\d+)/.exec(sql)![1]);
  // Retention pruning is time based; run the upgrade as if shortly after the fixture was taken.
  t.mock.timers.enable({ apis: ["Date"], now: generatedAt + 60_000 });
  const file = temp(t);
  const before = inspect(file, db => {
    db.exec(sql);
    return { version: schemaVersion(db), schema: schemaOf(db), rows: rowsOf(db) };
  });
  assert.equal(before.version, 2);
  const counts = Object.fromEntries(Object.entries(before.rows).map(([table, rows]) => [table, rows.length]));
  assert.ok(Object.entries(counts).every(([table, n]) => n > 0 || table === "sqlite_sequence"), "the fixture populates every table");

  const hive = open(t, file);
  assert.equal(schemaVersion(hive.db), LATEST_VERSION);
  const human = hive.getAgent("human");
  assert.ok(hive.listMessages(human, "general").messages.length > 0);
  hive.db.close();

  const after = inspect(file, db => ({ schema: schemaOf(db), rows: rowsOf(db) }));
  assert.deepEqual(Object.fromEntries(Object.entries(after.rows).map(([table, rows]) => [table, rows.length])), counts);
  assert.deepEqual(after.rows, before.rows, "an upgrade of a current-main hive only advances user_version");
  assert.deepEqual(after.schema, before.schema);
  open(t, file).db.close();
  assert.deepEqual(inspect(file, rowsOf), before.rows);
});

test("a newer user_version refuses to start and leaves the file untouched", t => {
  const file = temp(t);
  open(t, file).db.close();
  inspect(file, db => db.exec(`PRAGMA user_version = ${LATEST_VERSION + 1}`));
  const bytes = readFileSync(file);
  assert.throws(() => new Hive(file), new RegExp(`version ${LATEST_VERSION + 1}: it was written by a newer Hivemind`));
  assert.deepEqual(readFileSync(file), bytes);
});

test("a version this code never wrote is rejected", t => {
  const file = temp(t);
  open(t, file).db.close();
  inspect(file, db => db.exec("PRAGMA user_version = 1"));
  assert.throws(() => new Hive(file), /Unsupported storage schema version 1$/);
});

test("the version bump shares each step's transaction: a failure at any step rolls back only that step", t => {
  const original = DatabaseSync.prototype.exec;
  for (const migration of MIGRATIONS) {
    const file = temp(t);
    const stub = t.mock.method(DatabaseSync.prototype, "exec", function (this: DatabaseSync, sql: string) {
      original.call(this, sql);
      if (sql === `PRAGMA user_version = ${migration.version}`) throw new Error(`injected failure after ${migration.name}`);
    });
    try {
      assert.throws(() => new Hive(file), new RegExp(`injected failure after ${migration.name}`));
    } finally { stub.mock.restore(); }
    const expected = new DatabaseSync(":memory:");
    try {
      applyMigrations(expected, { target: migration.version - 1, validate: false });
      assert.deepEqual(inspect(file, db => ({ version: schemaVersion(db), schema: schemaOf(db) })),
        { version: migration.version === 3 ? 0 : migration.version - 1, schema: schemaOf(expected) }, migration.name);
    } finally { expected.close(); }
    const hive = new Hive(file);
    assert.equal(schemaVersion(hive.db), LATEST_VERSION);
    assert.deepEqual(schemaOf(hive.db), JSON.parse(fixture("main-schema.json")));
    hive.db.close();
  }
});

test("a real SQLite failure inside a legacy step rolls back its data changes; a restart completes it", t => {
  const file = temp(t);
  const hive = open(t, file);
  const brain = hive.join({ role: "brain" }).agent;
  // Reshape into a legacy hive without a project, so project_storage seeds one on upgrade.
  updateRows(hive, "agents", { project_id: null });
  updateRows(hive, "channels", { project_id: null });
  deleteRows(hive, "projects");
  markLegacyStorage(hive, 0);
  hive.db.close();
  // A second connection owns the persistent failure trigger and stays open across the failed start.
  const saboteur = new DatabaseSync(file);
  t.after(() => { try { saboteur.close(); } catch { /* closed below */ } });
  const restore = failWrites(saboteur, "projects", { message: "injected project seed failure", persistent: true });
  const before = rowsOf(saboteur);

  assert.throws(() => new Hive(file), /injected project seed failure/);
  assert.equal(inspect(file, schemaVersion), MIGRATIONS.find(m => m.name === "project_storage")!.version - 1);
  assert.deepEqual(inspect(file, db => rowsOf(db)), before, "no row of the failed step survives");

  restore();
  saboteur.close();
  const upgraded = open(t, file);
  assert.equal(schemaVersion(upgraded.db), LATEST_VERSION);
  assert.equal(upgraded.getAgent(brain.id).projectId, upgraded.listProjects()[0]!.id);
});
